# Generated by Django 2.1.5 on 2019-04-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Major Name', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Minor Name', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=20)),
                ('start_date', models.DateField(help_text='Enter the date you started working for the Data Engineering team')),
                ('end_date', models.DateField(blank=True, help_text='Enter the date you stopped working for the Data Engineering team (do not enter anything if you still work for the team)', null=True)),
                ('email', models.EmailField(help_text='Enter your Umich email', max_length=254)),
                ('umich_id', models.IntegerField(help_text='Enter your umichid')),
                ('phone_number', models.IntegerField(help_text='Enter your Phone Number')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('role', models.CharField(choices=[('MEM', 'Member'), ('SRE', 'Senior Editor')], default='MEM', max_length=3)),
                ('date_of_birth', models.DateField(help_text='Enter Your Birthday', null=True)),
                ('picture', models.ImageField(default='pictures/no-photo.jpg', max_length=400, upload_to='pictures/')),
            ],
            options={
                'verbose_name': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='People_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Major')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Minor')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=300)),
                ('description', models.TextField(help_text='Write Project description', max_length=100000)),
                ('start_date', models.DateField(help_text='Enter the project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter the project end date (leave blank if no end date)', null=True)),
                ('published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('backend_progress', models.CharField(choices=[('None', 'None'), ('Data Collection', 'Data Collection'), ('Data Cleaning', 'Data Cleaning'), ('Data Analysis', 'Data Analysis'), ('Insight Report', 'Insight Report')], default='None', help_text='Backend Progress Stages: (1) Data Collection, (2) Data Cleaning, (3) Data Analysis, (4) Insight Report. Please select the stage of the project last completed. If none of the stages are completed please select None.', max_length=100)),
                ('peoples', models.ManyToManyField(blank=True, default='None', help_text="Select all individuals who contributed to the project. (Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Project', to='catalog.People', verbose_name='contributors')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Null', help_text='Section', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Section', verbose_name='Section of Newspaper Published'),
        ),
        migrations.AddField(
            model_name='people_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Project'),
        ),
        migrations.AddField(
            model_name='people',
            name='majors',
            field=models.ManyToManyField(blank=True, default='Undeclared', help_text="Select your major(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Major', to='catalog.Major', verbose_name='Major(s)'),
        ),
        migrations.AddField(
            model_name='people',
            name='minors',
            field=models.ManyToManyField(blank=True, help_text="Select your minor(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Minor', to='catalog.Minor', verbose_name='Minor(s)'),
        ),
        migrations.AddField(
            model_name='people',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text="Select all Projects you have worked on.(Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Project', to='catalog.Project', verbose_name='Project(s)'),
        ),
        migrations.AddField(
            model_name='minor',
            name='peoples',
            field=models.ManyToManyField(through='catalog.People_Minor', to='catalog.People'),
        ),
        migrations.AddField(
            model_name='major',
            name='peoples',
            field=models.ManyToManyField(through='catalog.People_Major', to='catalog.People'),
        ),
    ]
