# Generated by Django 2.1.5 on 2019-04-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190412_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People_Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='major',
            name='peoples',
            field=models.ManyToManyField(blank=True, default='None', through='catalog.People_Major', to='catalog.People'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='peoples',
            field=models.ManyToManyField(blank=True, default='None', through='catalog.People_Minor', to='catalog.People'),
        ),
        migrations.AlterField(
            model_name='people',
            name='majors',
            field=models.ManyToManyField(blank=True, default='Undeclared', help_text="Select your major(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Major', to='catalog.Major', verbose_name='Major(s)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='minors',
            field=models.ManyToManyField(blank=True, help_text="Select your minor(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", through='catalog.People_Minor', to='catalog.Minor', verbose_name='Minor(s)'),
        ),
        migrations.AddField(
            model_name='people_minor',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Minor'),
        ),
        migrations.AddField(
            model_name='people_minor',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People'),
        ),
        migrations.AddField(
            model_name='people_major',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Major'),
        ),
        migrations.AddField(
            model_name='people_major',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People'),
        ),
    ]
