# Generated by Django 2.1.5 on 2019-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=20)),
                ('start_month', models.DateField(help_text='Enter the date you started working for the Data Engineering team')),
                ('end_month', models.DateField(blank=True, help_text='Enter the date you stopped working for the Data Engineering team', null=True)),
                ('email', models.EmailField(help_text='Enter your Umich email', max_length=254)),
                ('umich_id', models.IntegerField(help_text='Enter your umichid', max_length=100)),
                ('phone_number', models.IntegerField(help_text='Enter your Phone Number', max_length=100)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
