# Generated by Django 2.1.5 on 2019-02-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190203_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='date_of_birth',
            field=models.DateField(help_text='Enter Your Birthday', null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('MEM', 'Member'), ('SRE', 'Senior Editor')], default='MEM', max_length=2),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.IntegerField(help_text='Enter your Phone Number'),
        ),
        migrations.AlterField(
            model_name='people',
            name='umich_id',
            field=models.IntegerField(help_text='Enter your umichid'),
        ),
    ]
