# Generated by Django 2.1.5 on 2019-02-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190203_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='end_date',
            field=models.DateField(blank=True, help_text='Enter the date you stopped working for the Data Engineering team (do not enter anything if you still work for the team)', null=True),
        ),
    ]
