# Generated by Django 2.1.5 on 2019-02-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190205_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project Name', max_length=50)),
                ('description', models.TextField(help_text='Write Project description', max_length=2000)),
                ('start_date', models.DateField(help_text='Enter the project start date', null=True)),
                ('end_date', models.DateField(help_text='Enter the project end date', null=True)),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.People')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('published_id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=2)),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.People')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='published_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Published'),
        ),
    ]
