# Generated by Django 2.1.5 on 2019-02-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190205_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Enter the project end date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Published'),
        ),
    ]
