# Generated by Django 2.1.5 on 2019-03-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190205_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Major Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('minor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Minor Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People_Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Major')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Minor')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.People')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Null', help_text='Section', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='published',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='published',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_id',
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.DeleteModel(
            name='Published',
        ),
        migrations.AddField(
            model_name='people_project',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Project'),
        ),
        migrations.AddField(
            model_name='minor',
            name='members',
            field=models.ManyToManyField(related_name='minors', through='catalog.People_Minor', to='catalog.People'),
        ),
        migrations.AddField(
            model_name='major',
            name='members',
            field=models.ManyToManyField(related_name='majors', through='catalog.People_Major', to='catalog.People'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='catalog.People_Project', to='catalog.People'),
        ),
        migrations.AddField(
            model_name='project',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Section'),
        ),
    ]
