# Generated by Django 2.1.5 on 2019-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190322_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, default='Null', help_text='Section', max_length=50, null=True),
        ),
    ]
