# Generated by Django 2.1.5 on 2019-03-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190325_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='picture',
            field=models.ImageField(default='pictures/None/no-img.jpg', max_length=400, upload_to='pictures/'),
        ),
    ]
