# Generated by Django 2.1.5 on 2019-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_people_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='people',
            name='members',
            field=models.ManyToManyField(related_name='peoples', through='catalog.People_Project', to='catalog.Project'),
        ),
    ]
