# Generated by Django 2.1.5 on 2019-03-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190326_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_major',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='people_major',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='people_minor',
            name='minor_id',
        ),
        migrations.RemoveField(
            model_name='people_minor',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='people_project',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='people_project',
            name='project_id',
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='minor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='major',
            name='members',
        ),
        migrations.RemoveField(
            model_name='minor',
            name='members',
        ),
        migrations.AddField(
            model_name='people',
            name='members_major',
            field=models.ManyToManyField(blank=True, default='Undeclared', help_text="Select all your major(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", null=True, related_name='peoples', to='catalog.Major', verbose_name='Major(s)'),
        ),
        migrations.AddField(
            model_name='people',
            name='members_minor',
            field=models.ManyToManyField(blank=True, help_text="Select all your minor(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", null=True, related_name='peoples', to='catalog.Minor', verbose_name='Minor(s)'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text="Select all individuals who contributed to the project. (Hold down 'Control', or 'Command' on a Mac, to select more than one)", related_name='projects', to='catalog.People', verbose_name='contributors'),
        ),
        migrations.AlterField(
            model_name='people',
            name='members',
            field=models.ManyToManyField(blank=True, help_text="Select all Projects you have worked on.(Hold down 'Control', or 'Command' on a Mac, to select more than one)", null=True, related_name='peoples', to='catalog.Project', verbose_name='Project(s)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Section', verbose_name='Section of Newspaper Published'),
        ),
        migrations.DeleteModel(
            name='People_Major',
        ),
        migrations.DeleteModel(
            name='People_Minor',
        ),
        migrations.DeleteModel(
            name='People_Project',
        ),
    ]
