# Generated by Django 2.1.5 on 2019-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190327_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='members',
            field=models.ManyToManyField(blank=True, help_text="Select all Projects you have worked on.(Hold down 'Control', or 'Command' on a Mac, to select more than one)", related_name='peoples', to='catalog.Project', verbose_name='Project(s)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='members_major',
            field=models.ManyToManyField(blank=True, default='Undeclared', help_text="Select all your major(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", related_name='peoples', to='catalog.Major', verbose_name='Major(s)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='members_minor',
            field=models.ManyToManyField(blank=True, help_text="Select all your minor(s).(Hold down 'Control', or 'Command' on a Mac, to select more than one)", related_name='peoples', to='catalog.Minor', verbose_name='Minor(s)'),
        ),
    ]
